version: '3.7'

services:
  retrobuild:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: retrobuild
    expose:
      - '4321'
    ports:
      - '4321:4321'
    command: npm run dev